name: Build and release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Compile
        run: make -j$(nproc)
      - name: Archive
        run: tar -C build/release-linux-x86_64/ -czvf build/ioq3-instagram.tar.gz instagram/vm/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/ioq3-instagram.tar.gz'
          skipIfReleaseExists: true
